name: Issue Closed
on:
  issues:
    types: 
      - closed

jobs:
  webhook:
    name: Webhook Job
    runs-on:
      - ubuntu-latest
    steps:
      - name: Check out from Git
        uses: actions/checkout@v2
      - name: Webhook
        uses: joelwmale/webhook-action@749e2dcbc6735ce0c36e1dbbb660618cd7b5f91c
        env:
          WEBHOOK_URL: https://sssv0edjyjuz9eb.stakwork.sphinx.chat/action
          data: "{'bot_name': 'GithubBot', 'content': 'Issue #${{ github.event.issue.number }} in sphinx-relay closed!', 'action': 'broadcast', 'bot_id': '87B4FEE3DD71C2B0', 'bot_secret': '${{secrets.STACK_BOT_SECRET}}', 'chat_uuid': 'YWSFcR-fmmJZwP1N2VTjadIxhQyxPB2GpRLBcCVOvDOlJ6tNIUrBGQb2huaXg860-T435comee9vQ4w5J6MprVxGe175'}"

